compiler:
	jjtree Salsa0.3.jjt
	javacc Salsa0.3.jj
	javac *.java definitions/*.java
clean:
	rm Token.java TokenMgrError.java ParseException.java JavaCharStream.java -f
	rm *.class definitions/*.class -f	
